import type { Metadata } from 'next';
import Providers from '@/providers/hero-ui';
import '@/styles/globals.css';
import { fontMono, fontSans } from '@/configs/fonts';
import QueryProvider from '@/providers/query';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fontSans.variable} ${fontMono.variable} antialiased`}>
        <QueryProvider>
          <Providers themeProps={{ attribute: 'class', defaultTheme: 'dark' }}>
            {children}
          </Providers>
        </QueryProvider>
      </body>
    </html>
  );
}

